<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PowerGrind.FightEvents.Application\PowerGrind.FightEvents.Application.csproj" />
    <ProjectReference Include="..\PowerGrind.FightEvents.Domain\PowerGrind.FightEvents.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Http\Clients\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
